namespace ProjectHub.Api.Modules.Attachments;

/// <summary>
/// Binary storage for attachments. Keys are generated by ProjectHub and never derived from
/// user input. Azure Blob Storage replaces the local implementation before production.
/// </summary>
public interface IAttachmentStorage
{
    Task SaveAsync(string key, Stream content, CancellationToken ct);

    Task<Stream?> OpenReadAsync(string key, CancellationToken ct);

    Task DeleteAsync(string key, CancellationToken ct);
}

public sealed class AttachmentOptions
{
    public const string DirectoryKey = "PROJECTHUB_ATTACHMENT_DIRECTORY";
    public const string MaxSizeKey = "PROJECTHUB_ATTACHMENT_MAX_BYTES";

    /// <summary>Start value from DEC-007 (100 MB), to be confirmed by IT/Security.</summary>
    public const long DefaultMaxSizeBytes = 100L * 1024 * 1024;

    public required string Directory { get; init; }

    public long MaxSizeBytes { get; init; } = DefaultMaxSizeBytes;
}

/// <summary>Stores files in a local directory. For development and tests.</summary>
internal sealed class LocalAttachmentStorage(AttachmentOptions options) : IAttachmentStorage
{
    public async Task SaveAsync(string key, Stream content, CancellationToken ct)
    {
        var path = PathFor(key);
        System.IO.Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var file = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true);
        await content.CopyToAsync(file, ct);
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        Stream? stream = File.Exists(path) ? new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true) : null;
        return Task.FromResult(stream);
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        File.Delete(PathFor(key));
        return Task.CompletedTask;
    }

    private string PathFor(string key)
    {
        var root = Path.GetFullPath(options.Directory);
        var path = Path.GetFullPath(Path.Combine(root, key));
        if (!path.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("Storage key escapes the attachment directory.");
        }

        return path;
    }
}
