namespace ProjectHub.Api.Modules.Whiteboard;

/// <summary>
/// Binary storage for whiteboard snapshots (DEC-008). Keys are generated by ProjectHub. Azure Blob Storage
/// replaces the local implementation together with attachments (DEC-017).
/// </summary>
public interface IWhiteboardSnapshotStorage
{
    Task SaveAsync(string key, byte[] content, CancellationToken ct);

    Task<byte[]?> ReadAsync(string key, CancellationToken ct);

    Task DeleteAsync(string key, CancellationToken ct);
}

public sealed class WhiteboardOptions
{
    public const string DirectoryKey = "PROJECTHUB_WHITEBOARD_DIRECTORY";
    public const string CompactionIntervalKey = "PROJECTHUB_WHITEBOARD_COMPACTION_SECONDS";
    public const string QuietPeriodKey = "PROJECTHUB_WHITEBOARD_QUIET_SECONDS";

    public required string SnapshotDirectory { get; init; }

    /// <summary>How often each instance looks for whiteboards to compact; 0 switches the background service off.</summary>
    public TimeSpan CompactionInterval { get; init; } = TimeSpan.FromSeconds(5);

    /// <summary>A whiteboard is compacted once nobody changed it for this long …</summary>
    public TimeSpan QuietPeriod { get; init; } = TimeSpan.FromSeconds(5);

    /// <summary>… or as soon as this many updates piled up.</summary>
    public int MaxPendingUpdates { get; init; } = 200;

    /// <summary>Largest single update a client may push (ADR 0009).</summary>
    public int MaxUpdateBytes { get; init; } = 256 * 1024;
}

/// <summary>Stores snapshots in a local directory. For development and tests.</summary>
internal sealed class LocalWhiteboardSnapshotStorage(WhiteboardOptions options) : IWhiteboardSnapshotStorage
{
    public async Task SaveAsync(string key, byte[] content, CancellationToken ct)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllBytesAsync(path, content, ct);
    }

    public async Task<byte[]?> ReadAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        return File.Exists(path) ? await File.ReadAllBytesAsync(path, ct) : null;
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        File.Delete(PathFor(key));
        return Task.CompletedTask;
    }

    private string PathFor(string key)
    {
        var root = Path.GetFullPath(options.SnapshotDirectory);
        var path = Path.GetFullPath(Path.Combine(root, key));
        if (!path.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("Storage key escapes the whiteboard directory.");
        }

        return path;
    }
}
